network/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("<str:username>/following", views.followingPage, name="following"),
    path("upload", views.uploadPage, name="uploadImage"),
    
    
    #API Routes
    path("follow/<str:username>", views.follow, name="follow"),
    path("edit", views.editPost, name="edit"),
    path("like/<int:id>", views.likePost, name="toggleLike"),
    path("comment/<int:id>", views.createComment, name="comment"),
    path("delete/<int:id>", views.deletePost, name="delete"),
    path("delpic", views.deleteProfilePic, name="delPic"),
    path("description", views.description, name="description"),
    path("api", views.api),
    path("g/likers/<int:id>/i=<str:item>", views.getLikers),
    
    # Check last
    path("<str:name>", views.profile, name="profile"),
]

project4/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("network.urls")),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

network/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from network.storage import OverwriteStorage

def new_filename(instance, filename):
        basename, extension = filename.split('.')
        return f"{instance.id}_{instance.username}.{extension}"

class User(AbstractUser):
    followers = models.ManyToManyField('self', blank=True, related_name="followersList", symmetrical=False)
    following = models.ManyToManyField('self', blank=True, related_name="followingList", symmetrical=False)
    profilePic = models.ImageField(upload_to=new_filename, storage=OverwriteStorage(), null=True, blank=True)
    description = models.TextField(null=True, blank=True, default="")
    
    def getProfileURL(self):
        if self.profilePic and hasattr(self.profilePic, 'url'):
            return self.profilePic.url
        else:
            return "/static/network/images/defaultAvatar.png"
    
    def __str__(self):
        return f"{self.username}"
    
    def serialize(self):
        return {
            "id" : self.id,
            "username" : self.username,
            "first_name" : self.first_name,
            "last_name" : self.last_name,
            "followers" : [follower.username for follower in self.followers.all()],
            "following" : [following.username for following in self.following.all()],
            "profilePic" : self.getProfileURL(),
            "description" : self.description
        }
        
    def getAllFollowers(self):
        return [follower.serialize() for follower in self.followers.all()]
    
    def followerCount(self):
        return len(self.followers.all())
    
    def followingCount(self):
        return len(self.following.all())

  
class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, related_name="posts")
    content = models.TextField()
    time = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(User, blank=True, related_name="postLikes")
    # comments = models.ManyToManyField(Comment, blank=True, related_name="post", symmetrical=False)
    ordering = ['-time']
    
    def comments(self):
        commentList = Comment.objects.all().filter(post=self)
        return commentList
    
    def allLikes(self):
        userList = list(self.likes.all())
        for i in range(len(userList)):
            userList[i] = userList[i].username
        return userList
    
    def serialize(self):
        return {
            "id" : self.id,
            "user" : self.user.serialize(),
            "content" : self.content,
            "likes" : len(self.allLikes()),
            "likers" : [user.serialize() for user in self.likes.all()],
            "time" : self.time.strftime("%d-%m-%Y, %I:%M %p"),
            "numComments" : len(self.comments())
        }
        
class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comments")
    comment = models.TextField()
    time = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(User, blank=True, related_name="commentLikes", symmetrical=False)
    postID = models.IntegerField(blank=True, null=True)
    post = models.ForeignKey(Post, blank=True, null=True, on_delete=models.CASCADE, related_name="post")
    
    class Meta:
        ordering = ['-time']
    
    def allLikes(self):
        userList = list(self.likes.all())
        for i in range(len(userList)):
            userList[i] = userList[i].username
        return userList
    
    def __str__(self):
        return f"Comment by {self.user} on post {self.postID}: {self.comment}"
    
    def serialize(self):
        return {
            "id" : self.id,
            "user" : self.user.serialize(),
            "comment" : self.comment,
            "likes" : len(self.allLikes()),
            "post" : self.post.serialize(),
            "time" : self.time.strftime("%b %d %Y, %I:%M %p"),
            "likers" : [user.serialize() for user in self.likes.all()],
        }

network/forms.py
from django.forms import ModelForm
from django import forms
from .models import User

class ImageUploadForm(ModelForm):
    class Meta:
        model = User
        fields = ['profilePic']
        
class DifferentImageUploadForm(forms.Form):
    image = forms.ImageField(label="Profile Picture: ")

network/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.urls import reverse
from django.core.paginator import Paginator
from django.db.models import Q
from collections import defaultdict
import json

from .models import User, Post, Comment
from .forms import ImageUploadForm
from . import utils


def index(request):
    user = request.user
    print(user)
    print("GET Request has been called")
    if not user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))
    postsList = Post.objects.order_by("-time").all()
    paginator = Paginator(postsList, 10)
    page_number =  request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    # Randomly selected profiles
    pYouMayKnow = utils.getRandomProfiles(user)
    pAlsoViewed = utils.getRandomProfiles(user)
    
    if request.method == 'POST':
        print("POST request has been called")
        data = json.loads(request.body)
        content = data.get("content","")
        post = utils.createPost(user, content)
        return JsonResponse({"message" : "Comment created",
                             "post" : post.serialize(),
                             }, status=200, safe=False)
    return render(request, "network/index.html", {
        "postsList" : postsList,
        "page_obj" : page_obj,
        "pYouMayKnow" : pYouMayKnow,
        "pAlsoViewed" : pAlsoViewed
    })

    
def profile(request, name):
    user = request.user
    if not user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))
    profile = User.objects.get(username=name)
    userFollowingList = user.following.all()
    profileFollowingList = profile.following.all()
    profileFollowersList = profile.followers.all()
    followedStatus = False
    # Alternate method, in case I forget
    # Use get() method on the QuerySet returned by user.following.all() to directly get the profile
    # If it returns a profile, make followedStatus = True, else do nothing.
    try:
        followedProfile = userFollowingList.get(id=profile.id)
        print("You follow this person")
        followedStatus = True
    except User.DoesNotExist:
        pass
    # All posts by the profile
    postsList = Post.objects.filter(user=profile.id).order_by("-time")
    paginator = Paginator(postsList, 10)
    page_number =  request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    likers = [post.serialize() for post in postsList]
    # print("Likers are = ", likers)
    x = defaultdict(list)
    for post in postsList:
        d = post.serialize()
        x[d["id"]].append(d["likers"])
    # print(x)
    # Randomly selected profiles
    pYouMayKnow = utils.getRandomProfiles(user)
    pAlsoViewed = utils.getRandomProfiles(user)
    
    # Form to upload image
    form = ImageUploadForm()
    if request.method == "POST":
        form = ImageUploadForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
        print(request.FILES, request.POST)
    
    return render(request, "network/profile.html", {
        "profile" : profile,
        "followedStatus" : followedStatus,
        "postsList" : postsList,
        "page_obj" : page_obj,
        "pFollowingList" : profileFollowingList,
        "pFollowersList" : profileFollowersList,
        "likers" : likers,
        "pYouMayKnow" : pYouMayKnow,
        "pAlsoViewed" : pAlsoViewed,
        "form" : form
    })

@login_required
def followingPage(request, username):
    user = request.user
    if not user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))
    profileFollowingList = user.following.all()
    postsList = []
    for profile in profileFollowingList:
        posts = Post.objects.all().filter(user=profile)
        for post in posts:
            postsList.append(post)
    postsList = utils.sortByTime(postsList)
    paginator = Paginator(postsList, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    x = defaultdict()
    if len(postsList) == 0:
        return HttpResponseRedirect(reverse('index'))
    for post in postsList:
        d = post.serialize()
        # x[d["id"]].append(d["likers"])
    # Randomly selected profiles
    pYouMayKnow = utils.getRandomProfiles(user)
    pAlsoViewed = utils.getRandomProfiles(user)
    
    return render(request, "network/following.html", {
        "postsList" : postsList,
        "page_obj" : page_obj,
        "pYouMayKnow" : pYouMayKnow,
        "pAlsoViewed" : pAlsoViewed
    })
    
def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "network/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "network/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]
        first_name = request.POST["first_name"]
        last_name = request.POST["last_name"]
        
        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "network/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create(first_name=first_name, last_name=last_name, username=username, email=email, password=password )
            password = user.set_password(raw_password=password)
            user.save()
        except IntegrityError:
            return render(request, "network/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "network/register.html")
    

@login_required
def follow(request, username):
    print("Username is : ",username)
    user = request.user
    data = json.loads(request.body)
    buttonValue = data.get("buttonValue", "")
    print(user)
    try:
        followTarget = User.objects.get(username=username)
    except User.DoesNotExist:
        followTarget = User.objects.get(username=username[0].lower()+username[1:])
    if (buttonValue == 'Follow'):
        if followTarget == user:
            return JsonResponse({"error" : "You cannot follow yourself"}, status=400)
        
        followTarget.followers.add(user)
        user.following.add(followTarget)
        return JsonResponse({ "message": "Followed successfully", "user" : user.serialize() }, status=200)
    elif buttonValue == 'Unfollow':
        followTarget.followers.remove(user)
        user.following.remove(followTarget)
        return JsonResponse({"message" : "Unfollowed successfully", "user" : user.serialize() }, status=200)

def editPost(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        content = data.get("content", "")
        item = data.get("item", "")
        id = data.get("id", "")
        
        if item == 'post':
            try:
                post = Post.objects.get(id=id)
                post.content = content
                post.save()
            except Post.DoesNotExist :
                print("Post does not exist")
                return JsonResponse({"error" : "Couldn't find post"}, status=404)
            return JsonResponse({"message" : f"Post No. {id} edited successfully"}, status=200)
        elif item == 'comment':
            try:
                comment = Comment.objects.get(id=id)
                comment.comment = content
                comment.save()
            except Comment.DoesNotExist:
                return JsonResponse({"error" : "Couldn't find comment"}, status=404)
            return JsonResponse({"message" : f"Comment No. {id} edited successfully"}, status=200)
    
def likePost(request, id):
    user = request.user
    data = json.loads(request.body)
    item = data.get("item", "")
    status = data.get("status", "")
    
    if item == 'post':
        post = Post.objects.get(id=id)        
        print("Content is ", status)
        if status == 'Like':
            post.likes.add(user)
            post.save()
            return JsonResponse({"message": f"{user} has liked Post No. {id}"}, status=200)
        else:
            post.likes.remove(user) 
            post.save()
            return JsonResponse({"message": f"{user} has unliked Post No. {id}"}, status=200)
        
    elif item == 'comment':
        comment = Comment.objects.get(id=id)
        if status == 'Like':
            comment.likes.add(user)
            comment.save()
            return JsonResponse({"message" : f"{user} has liked Comment No. {id}"}, status=200)
        else:
            comment.likes.remove(user)
            comment.save()
            return JsonResponse({"message" : f"{user} has unliked Comment No. {id}"}, status=200)
        
    else :
        return JsonResponse({"error" : "The item is neither post nor comment"}, status=500)
    
def deletePost(request, id):
    user = request.user
    data = json.loads(request.body)
    itemType = data.get("item", "")
    if itemType == 'post':

network/templates/network/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <title>{% block title %}Social Network{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="{% static 'network/styles.css' %}" rel="stylesheet">
    <script src="https://kit.fontawesome.com/e46601e7fc.js" crossorigin="anonymous"></script>
    <script src="{% static 'network/network.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>
</head>

<body>
    <nav class="navbar navbar-expand-md sticky-top navbar-dark bg-dark d-none d-md-block">
        <a class="navbar-brand" href="{% url 'index' %}">Network</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        <div class="d-inline-flex" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link"
                        href="{% url 'profile' user.username %}"><strong id="username">{{ user.username }}</strong></a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'index' %}">All Posts</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'following' request.user.username %}">Following</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'register' %}">Register</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <nav class="navbar navbar-expand-lg fixed-bottom navbar-dark bg-dark d-block d-md-none">
        <div class="flex row justify-content-between" id="navbarSupportedContent">
            <a class="nav-link menuBarItem" href="{% url 'index' %}">
                <i class="fas fa-home menuBarIcon"></i>
                <br>
                All Posts
            </a>
            {% if user.is_authenticated %}
            <a class="nav-link menuBarItem"
                href="{% url 'profile' user.username %}">
                <i class="fas fa-user-circle menuBarIcon"></i> 
                <br>
                Your Profile
                <!-- <strong id="username">Your Profile</strong> -->
            </a>
            <a class="nav-link menuBarItem " style="padding: 4px 8px;"
                href="{% url 'index' %}">
                <i class="fas fa-plus-circle menuBarIcon"></i> 
                <br>
                Post
            </a>
            <a class="nav-link menuBarItem" href="{% url 'following' request.user.username %}">
                <i class="fas fa-users menuBarIcon"></i>
                <br>
                Following
            </a>
            <a class="nav-link menuBarItem" href="{% url 'logout' %}">
                <i class="fas fa-sign-out-alt menuBarIcon"></i>
                <br>
                Log Out
            </a>
            {% else %}
            <a class="nav-link menuBarItem" href="{% url 'login' %}">Log In</a>
            <a class="nav-link menuBarItem" href="{% url 'register' %}">Register</a>
            {% endif %}
        </div>
    </nav>

    <div class="body pb-5 pb-md-0">
        {% block body %}
        {% endblock %}
    </div>
</body>

</html>

network/templates/network/login.html
{% load static %}

<!DOCTYPE html>

<head>
    <title>Login</title>
    <meta name="viewport" content="width= device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="{% static 'network/styles.css' %}" rel="stylesheet">
</head>

<body>
    <div class="container p-0" style="height: 100vh; max-width: 100%;">
        <div class="row m-0" style="height: 100%; width: 100%;">
            <div class="col-md-6 col-lg-7 d-none d-md-block" style="background-color: #5372f8;"></div>
            <div class="col-md-6 col-lg-5 align-self-center " style="padding: 0 80px">
                <h2>Login</h2>
                {% if message %}
                <div>{{ message }}</div>
                {% endif %}
                <form action="{% url 'login' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <input autofocus class="form-control" type="text" name="username" placeholder="Username">
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="password" name="password" placeholder="Password">
                    </div>
                    <input class="btn btn-primary" type="submit" value="Login">
                </form>
                Don't have an account? <a href="{% url 'register' %}">Register here.</a>
            </div>
        </div>
    </div>

</body>

network/templates/network/register.html
{% load static %}

<!DOCTYPE html>

<head>
    <title>Register</title>
    <meta name="viewport" content="width= device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="{% static 'network/styles.css' %}" rel="stylesheet">
</head>

<body style="background-color: #5372f8;">
    <div class="container p-0" style="height: 100vh; max-width: 100%;">
        <div class="row m-0" style="height: 100%; width: 100%;">
            <!-- <div class="col-12" style="background-color: #5372f8;"></div> -->
            <div class="col-11 col-sm-6 col-md-5 col-lg-4 align-self-center register-form ">
                <div class="row-col">
                    <h2 class="text-center" style="font-weight: 400">Register</h2>

                    {% if message %}
                    <div>{{ message }}</div>
                    {% endif %}

                    <form action="{% url 'register' %}" method="post" id="register-form">
                        {% csrf_token %}
                        <div class="form-page" id="form-page-1">
                            <div class="form-row">
                                <div class="form-group col-md">
                                    <label for="first-name">First Name</label>
                                    <input class="form-control" type="text" name="first_name">
                                </div>
                                <div class="form-group col-md">
                                    <label for="last-name">Last Name</label>
                                    <input class="form-control" type="text" name="last_name">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="username">Username</label>
                                <input class="form-control" type="text" name="username">
                            </div>
                            <button class="btn btn-primary" type="button" value="Next" id="nextButton">Next</button>
                        </div>
                        <div class="form-page" id="form-page-2">
                            <div class="form-group">
                                <label for="email">Email</label>
                                <input class="form-control" type="email" name="email">
                            </div>
                            <div class="form-group">
                                <label for="password">Password</label>
                                <input class="form-control" type="password" name="password" >
                            </div>
                            <div class="form-group">
                                <label for="confirmation">Confirm Password</label>
                                <input class="form-control" type="password" name="confirmation">
                            </div>
                            <button class="btn btn-primary" type="button" value="Back" id="backButton">Back</button>
                            <input class="btn btn-primary" type="submit" value="Register" id="register">
                        </div>

                    </form>
                </div>

                <!-- <hr>
                Already have an account? <a href="{% url 'login' %}">Log In here.</a> -->
                <div class="register-footer">
                    Already have an account? <a href="{% url 'login' %}">Log In here.</a>
                </div>
            </div>
        </div>
    </div>
    <script>
        const slideForm = document.querySelector('#register-form');
        const page1 = document.querySelector('#form-page-1');
        const page2 = document.querySelector('#form-page-2');
        const formContainer = document.querySelector('.register-form');
        const registerFooter = document.querySelector('.register-footer');
        const nextButton = document.querySelector('#nextButton');
        nextButton.onclick = function leftSlide() {
            page2.style.display = 'block';
            slideForm.style.marginLeft = "-100%";
        }

        const backButton = document.querySelector('#backButton');
        backButton.onclick = function rightSlide() {
            page1.style.display = 'block';
            slideForm.style.marginLeft = "0";
            page2.style.display = 'none';
            
        }
    </script>
</body>

network/templates/network/upload.html
{% extends 'network/layout.html' %}
{% load static %}

{% block body %}

<div class="container mt-5 text-center">

    <h2>Image Preview</h2>
    <div
        style="background-color: lightgrey; width: 250px; height: 250px; overflow: hidden; border-radius: 50%; margin: 30px auto;">
        {% if request.user.profilePic %}
        <img id="output" src="{{request.user.profilePic.url}}"
            style="width: 250px; height:250px; object-fit:cover; border-radius: 50%" />
        {% else %}
        <img id="output" src="/static/network/images/defaultAvatar.png" style="width: 250px; height:250px; object-fit:cover; border-radius: 50%" />
        {% endif %}
    </div>
    <div id="imgLookMessage">This is what the image will look like.
        <div style="font-size: 0.9em; color:grey">For best fit, use a square image</div>
    </div>
    {% if not discard %}
    <div id="updatedMessage">Profile picture has been updated!</div>
    {% endif %}
    <label for="id_profilePic" class="btn btn-primary my-4" style="cursor: pointer;">Select Image</label>
    <form action="" method="POST" enctype="multipart/form-data" id="profilePicForm" name="profilePicForm"
        style="display: none;">
        {% csrf_token %}
        {{form.as_p}}
        
    </form>
    <button form="profilePicForm" type="submit" class="btn btn-success" data-user={{profile.id}} id="uploadPicButton">Save</button>

    {% if discard %}
    <a href="{% url 'profile' request.user.username %}" class="btn btn-danger" id="returnToProfile">Discard Changes</a>
    {% else %}
    <a href="{% url 'profile' request.user.username %}" class="btn btn-light border border-alert" id="returnToProfile">Go to Profile</a>
    {% endif %}

    <script>
        document.querySelector('#id_profilePic').onchange = function (event) {
            var image = document.getElementById('output');
            image.src = URL.createObjectURL(event.target.files[0]);
            document.querySelector('#imgLookMessage').style.display = 'block';
            document.querySelector('#updatedMessage').style.display = 'none';
        };
    </script>
</div>


{% endblock %}